package com.lishibook.entity;

import java.io.Serializable;
import java.util.Date;

public class ResourceTopicReply implements Serializable{
    
	private static final long serialVersionUID = 8649116822886314646L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_topic_reply.id
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_topic_reply.tid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Integer tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_topic_reply.authorid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Integer authorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_topic_reply.time
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_topic_reply.content
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_topic_reply.id
     *
     * @return the value of resource_topic_reply.id
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_topic_reply.id
     *
     * @param id the value for resource_topic_reply.id
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_topic_reply.tid
     *
     * @return the value of resource_topic_reply.tid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_topic_reply.tid
     *
     * @param tid the value for resource_topic_reply.tid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_topic_reply.authorid
     *
     * @return the value of resource_topic_reply.authorid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Integer getAuthorid() {
        return authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_topic_reply.authorid
     *
     * @param authorid the value for resource_topic_reply.authorid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setAuthorid(Integer authorid) {
        this.authorid = authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_topic_reply.time
     *
     * @return the value of resource_topic_reply.time
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_topic_reply.time
     *
     * @param time the value for resource_topic_reply.time
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_topic_reply.content
     *
     * @return the value of resource_topic_reply.content
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_topic_reply.content
     *
     * @param content the value for resource_topic_reply.content
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setContent(String content) {
        this.content = content;
    }
}