package com.lishibook.entity;

import java.io.Serializable;
import java.util.Date;

public class ResourceFocusgroup implements Serializable{
    
	private static final long serialVersionUID = 8323269932821476938L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_focusgroup.id
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_focusgroup.rid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_focusgroup.name
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_focusgroup.desc
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_focusgroup.time
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_focusgroup.id
     *
     * @return the value of resource_focusgroup.id
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_focusgroup.id
     *
     * @param id the value for resource_focusgroup.id
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_focusgroup.rid
     *
     * @return the value of resource_focusgroup.rid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_focusgroup.rid
     *
     * @param rid the value for resource_focusgroup.rid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_focusgroup.name
     *
     * @return the value of resource_focusgroup.name
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_focusgroup.name
     *
     * @param name the value for resource_focusgroup.name
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_focusgroup.desc
     *
     * @return the value of resource_focusgroup.desc
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_focusgroup.desc
     *
     * @param desc the value for resource_focusgroup.desc
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_focusgroup.time
     *
     * @return the value of resource_focusgroup.time
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_focusgroup.time
     *
     * @param time the value for resource_focusgroup.time
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setTime(Date time) {
        this.time = time;
    }
}