package com.lishibook.entity;

import java.io.Serializable;
import java.util.Date;

public class UserCollections implements Serializable {
    
	private static final long serialVersionUID = 96795110951783092L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_collections.id
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_collections.uid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_collections.rid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_collections.time
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_collections.id
     *
     * @return the value of user_collections.id
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_collections.id
     *
     * @param id the value for user_collections.id
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_collections.uid
     *
     * @return the value of user_collections.uid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_collections.uid
     *
     * @param uid the value for user_collections.uid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_collections.rid
     *
     * @return the value of user_collections.rid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_collections.rid
     *
     * @param rid the value for user_collections.rid
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_collections.time
     *
     * @return the value of user_collections.time
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_collections.time
     *
     * @param time the value for user_collections.time
     *
     * @mbggenerated Mon Mar 03 21:09:16 CST 2014
     */
    public void setTime(Date time) {
        this.time = time;
    }
}